server:
  port: 9092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course_service
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: COURSE-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
