server:
  port: 9093

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: rating_service
  application:
    name: RATING-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka